server:
  ssl:
    enabled: false
zeikona:
  o-auth2-credential:
    installed:
      client_id: 13487503673-gi2lgdd7h5a4gn87rs602ct7q83qthf3.apps.googleusercontent.com
      client_secret: RgkQF0KmXFFWJTFq10Y2CA6v
      
logging:
  level:
    org.mdkt.zeikona: DEBUG